nome = input("Qual é seu nome?")
curso = input("Qual é seu curso?")
idade = input("Qual é sua idade?")
time_favorito = input("Qual é seu time de futebol favorito?")
cidade_Natal = input("Qual é sua cidade natal?")
cor_favorita = input("Qual é sua cor favorita?")
comida_favorita = input("Qual é sua comida favorita?")


print("Qual seu nome", nome, "Qual é seu curso", curso, "Qual é sua idade", idade, "Qual é seu time de futebol favorito", time_favorito, "Qual é sua cidade natal", cidade_Natal, "Qual é sua cor favorita", cor_favorita, "Qual é sua comida favorita", comida_favorita    )

print("\n==============================")
print("       CARTÃO DE APRESENTAÇÃO")
print("==============================")
print("Nome:   " + nome)
print("Curso:  " + curso)
print("Idade:  " + idade)
print("Time:   " + time_favorito)
print("Cidade: " + cidade_Natal)
print("Cor:    " + cor_favorita)
print("Comida: " + comida_favorita)

print("==============================")




print(".    .")
print("   ^  ")
print("/\_/\ ")

print("5 * 1 = 5")
print("5 * 2 = 10")
print("5 * 3 = 15")
print("5 * 4 = 20")
print("5 * 5 = 25")
print("5 * 6 = 30")
print("5 * 7 = 35")
print("5 * 8 = 40")
print("5 * 9 = 45")
print("5 * 10 = 50")


