print('Oi ! Quero te conhecer')
João  = input("Qual é o seu nome?")
print('oi '+ João )
dezoito = input("Digite sua idade")
print('Sua idade é '+ dezoito + ' anos')
NaoQueroFalar = input("Digite sua data de nascimento")
print('sua data de nascimento é '+ NaoQueroFalar )
Sorvete = input("Qual é sua comida favorita?")
print('Sua comida favorita é '+ Sorvete )
FatecRioClaro = input("Qual é sua faculdade?")
print('Sua faculdade é '+ FatecRioClaro )
AmelhordoBrasil = input("E ela é boa?")
print('A melhor do Brasil é '+ AmelhordoBrasil )
